import type { ComponentType } from "react";
import {
  Home,
  Building2,
  Bed,
  Bath,
  Zap,
  Flame,
  Droplet,
  Wifi,
  Phone,
  Laptop,
  Monitor,
  Smartphone,
  ShoppingCart,
  ShoppingBag,
  Utensils,
  Coffee,
  Cookie,
  Apple,
  Car,
  Bus,
  Fuel,
  Bike,
  Plane,
  TrainFront,
  Heart,
  Pill,
  Stethoscope,
  Activity,
  Baby,
  GraduationCap,
  BookOpen,
  BookMarked,
  Gamepad2,
  Music,
  Film,
  Tv,
  Dumbbell,
  PawPrint,
  Shield,
  Umbrella,
  Wrench,
  Hammer,
  Scissors,
  Shirt,
  Sparkles,
  Gift,
  PartyPopper,
  PiggyBank,
  Wallet,
  CreditCard,
  Banknote,
  Landmark,
  TrendingUp,
  Briefcase,
  Target,
  Star,
  Tag,
  Bookmark,
  Flag,
  Sun,
  Leaf,
  TreeDeciduous,
} from "lucide-react";

export type IconComponent = ComponentType<{ size?: number; strokeWidth?: number }>;

/**
 * Curated icon map. Using named imports (rather than `import * as Lucide`)
 * lets the bundler tree-shake — only these ~60 icons ship, not all ~1500.
 * Keys are the kebab-case names users save in Category.icon.
 */
export const ICON_MAP: Record<string, IconComponent> = {
  "home": Home,
  "building-2": Building2,
  "bed": Bed,
  "bath": Bath,
  "zap": Zap,
  "flame": Flame,
  "droplet": Droplet,
  "wifi": Wifi,
  "phone": Phone,
  "laptop": Laptop,
  "monitor": Monitor,
  "smartphone": Smartphone,
  "shopping-cart": ShoppingCart,
  "shopping-bag": ShoppingBag,
  "utensils": Utensils,
  "coffee": Coffee,
  "cookie": Cookie,
  "apple": Apple,
  "car": Car,
  "bus": Bus,
  "fuel": Fuel,
  "bike": Bike,
  "plane": Plane,
  "train-front": TrainFront,
  "heart": Heart,
  "pill": Pill,
  "stethoscope": Stethoscope,
  "activity": Activity,
  "baby": Baby,
  "graduation-cap": GraduationCap,
  "book-open": BookOpen,
  "book-marked": BookMarked,
  "gamepad-2": Gamepad2,
  "music": Music,
  "film": Film,
  "tv": Tv,
  "dumbbell": Dumbbell,
  "paw-print": PawPrint,
  "shield": Shield,
  "umbrella": Umbrella,
  "wrench": Wrench,
  "hammer": Hammer,
  "scissors": Scissors,
  "shirt": Shirt,
  "sparkles": Sparkles,
  "gift": Gift,
  "party-popper": PartyPopper,
  "piggy-bank": PiggyBank,
  "wallet": Wallet,
  "credit-card": CreditCard,
  "banknote": Banknote,
  "landmark": Landmark,
  "trending-up": TrendingUp,
  "briefcase": Briefcase,
  "target": Target,
  "star": Star,
  "tag": Tag,
  "bookmark": Bookmark,
  "flag": Flag,
  "sun": Sun,
  "leaf": Leaf,
  "tree-deciduous": TreeDeciduous,
};

export const ICONS = Object.keys(ICON_MAP) as IconName[];

export type IconName = keyof typeof ICON_MAP | string;

/** Fallback when a saved icon name doesn't exist in the current set. */
export const DEFAULT_ICON = "tag";

export function resolveIcon(name: string | undefined): IconComponent | null {
  if (!name) return ICON_MAP[DEFAULT_ICON] ?? null;
  return ICON_MAP[name] ?? ICON_MAP[DEFAULT_ICON] ?? null;
}
